MESSAGE_FORMAT_PARTY_PARTICIPATE = "{user} 님이 {party} 모임에 신청하셨습니다."
MESSAGE_FORMAT_PARTY_ACCEPTED = "{party} 모임에 참가 수락되었습니다."
MESSAGE_FORMAT_PARTY_REJECTED = "{party} 모임에 참가 거절되었습니다."
MESSAGE_FORMAT_PARTY_CANCELED = "{user} 님이 {party} 모임에 참가를 취소하였습니다."
MESSAGE_FORMAT_PARTY_COMMENT_ADDED = "{user} 님이 {party} 모임에 댓글을 달았습니다."
MESSAGE_FORMAT_PARTY_DETAILS_CHANGED = "{party} 모임 정보가 변경되었습니다."
MESSAGE_FORMAT_PARTY_HAS_DEACTIVATED = "{party} 모임가 마감되었습니다."
