# AUTH PLATFORM
AUTH_PLATFORM_GOOGLE = "google"
AUTH_PLATFORM_NAVER = "naver"
AUTH_PLATFORM_KAKAO = "kakao"


# DATETIME FORMAT
FORMAT_YYYY_MM_DD = "%Y-%m-%d"
FORMAT_YYYYMMDD = "%Y%m%d"
FORMAT_YYYY_MM_DD_T_HH_MM_TZ = "%Y-%m-%dT%H:%M%z"
FORMAT_YYYY_MM_DD__HH_MM_SS = "%Y-%m-%d %H:%M:%S"
FORMAT_YYYY_MM_DD_T_HH_MM_SS = "%Y-%m-%dT%H:%M:%S"
FORMAT_YYYY_MM_DD_T_HH_MM_SS_TZ = "%Y-%m-%dT%H:%M:%S%z"
FORMAT_YYYY_MM_DD__HH_MM_SS_MS = "%Y-%m-%d %H:%M:%S.%f"
FORMAT_YYYY_MM_DD_T_HH_MM_SS_MS = "%Y-%m-%dT%H:%M:%S.%f"
FORMAT_YYYY_MM_DD_T_HH_MM_SS_MS_TZ = "%Y-%m-%dT%H:%M:%S.%f%z"

FORMAT_YYYY_d_MM_d_DD__HH_MM = "%Y.%m.%d %H:%M"
FORMAT_HH_MM = "%H:%M"

# NOTIFICATIONS
NOTIFICATION_TYPE_ALL = "all"
NOTIFICATION_TYPE_PARTY = "party"
