# MIXPANEL EVENT NAMES
MIXPANEL_EVENT_SIGN_UP = "sign_up"
MIXPANEL_EVENT_SIGN_IN = "sign_in"
MIXPANEL_EVENT_LOGOUT = "log_out"
MIXPANEL_EVENT_PARTY_CREATE = "party_create"
MIXPANEL_EVENT_PARTY_UPDATE = "party_update"
MIXPANEL_EVENT_LIKE_PARTY = "like_party"
MIXPANEL_EVENT_CANCEL_LIKE_PARTY = "cancel_like_party"
MIXPANEL_EVENT_DELETE_PARTY = "delete_party"
MIXPANEL_EVENT_PARTY_PARTICIPATE = "party_participate"
MIXPANEL_EVENT_CHANGE_PARTY_PARTICIPATION_STATUS = "change_participation_status"
MIXPANEL_EVENT_ORGANIZER_CHANGE_PARTY_PARTICIPATION_STATUS = (
    "organizer_change_participation_status"
)
MIXPANEL_EVENT_VIEW_PARTY_DETAIL = "view_party_detail"
MIXPANEL_EVENT_PARTY_COMMENT = "write_comment"
MIXPANEL_EVENT_CHANGE_PROFILE = "change_profile"
MIXPANEL_EVENT_CHANGE_PROFILE_IMAGE = "change_profile_image"
MIXPANEL_EVENT_VIEW_NOTIFICATIONS = "view_notifications"
MIXPANEL_EVENT_READ_NOTIFICATIONS = "read_notifications"

# MIXPANEL PROPERTY KEY
MIXPANEL_PROPERTY_KEY_USER_ID = "$user_id"
MIXPANEL_PROPERTY_KEY_PARTY_PARTICIPATION_STATUS = "party_participation_status"
MIXPANEL_PROPERTY_KEY_PARTY_ID = "party_id"
MIXPANEL_PROPERTY_KEY_PARTY_PARTICIPATION_ID = "party_participation_id"

# MIXPANEL PROPERTIES
